# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 12:30
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u6b63\u6587'),
        ),
    ]
